[versions]
kotlin = "2.4.20"
kotlinx-io = "0.9.1"
kotlinx-html = "0.12.0"
kotlinxCoroutines = "1.11.0"
serialization = "1.11.0"
kotlinxDatetime = "0.8.0"
hash = "0.5.6"
macs = "0.8.0"
ktorHttp = "3.5.2"
linuxUring = "2.15.3"
linuxPlatform = "1.0.1"
openssl = "4.0.1.1"
mavenPublish = "0.37.0"

[libraries]
kotlinx-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-html = { group = "org.jetbrains.kotlinx", name = "kotlinx-html", version.ref = "kotlinx-html" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
hash-md5 = { group = "org.kotlincrypto.hash", name = "md5", version.ref = "hash" }
hash-sha1 = { group = "org.kotlincrypto.hash", name = "sha1", version.ref = "hash" }
hash-sha2 = { group = "org.kotlincrypto.hash", name = "sha2", version.ref = "hash" }
macs-hmac-sha2 = { group = "org.kotlincrypto.macs", name = "hmac-sha2", version.ref = "macs" }
ktor-http = { group = "io.ktor", name = "ktor-http", version.ref = "ktorHttp" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
linux-uring = { group = "io.github.kio-labs", name = "linux-uring", version.ref = "linuxUring" }
linux-platform = { group = "io.github.kio-labs", name = "linux-platform", version.ref = "linuxPlatform" }
openssl = { group = "io.github.kio-labs", name = "openssl", version.ref = "openssl" }

maven-publish-gradle-plugin = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "mavenPublish" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
